### ISSUE TITLE
5.1.1 版本的 angular 前端项目 build 时，报错

### ISSUE THREAD

**Issue by webliuxiang** [52ABP/YoyoCmsFree.Template#32]
项目版本：v5.1.1
错误详情：
在build前端项目时，报错
![image](https://user-images.githubusercontent.com/25944130/88520939-db039080-d026-11ea-867e-64433780ece2.png)
错误位置：
![image](https://user-images.githubusercontent.com/25944130/88521588-ae03ad80-d027-11ea-9662-35862572d9c4.png)

**Comment by ltm0203** [comment]
具体的报错信息呢。

**Comment by webliuxiang** [comment]
更新了，刚才点错了
@ltm0203
