### ISSUE TITLE
pro版本build报错

### ISSUE THREAD

**Issue by webliuxiang** [52ABP/YoyoCmsFree.Template#34]
pro版本前端项目build报错
![image](https://user-images.githubusercontent.com/25944130/88897831-7fcbdb00-d27e-11ea-987a-6118d497b64c.png)

version：3.1.0

**Comment by webliuxiang** [comment]
@ltm0203

**Comment by ltm0203** [comment]
你这个是你的npm前端包还原问题。和你网路环境有关。

pro版本请前往 http://code.52abp.com/commercial/ultimate  提交 问题。
